const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');let trial,writes=0,confirm=true;
const ctx=vm.createContext({crypto:require('node:crypto').webcrypto,structuredClone,secureShuffle:x=>[...x],normalizeBreedCode:x=>x,courseSizesForEntryCount:n=>[n],bifState:t=>t.scorebook.bif,readForm:()=>structuredClone(trial),selectedBifEntryIds:b=>new Set(b.selectedEntryIds),bifCandidateHoundsForTrial:t=>t.scorebook.bif.bieCandidates,upsertTrial:t=>{trial=t;writes++},saveTrials:()=>{},render:()=>{},showMessage:()=>{},showTrialConfirm:async()=>confirm,bifMessage:{},manualDrawEditKey:'',normalizeBifDrawColors:d=>({...d,courses:d.courses.map(c=>({...c,hounds:c.hounds.map((h,i)=>({...h,bifBlanketColor:['YELLOW','PINK','BLUE'][i]}))}))})});
vm.runInContext(fs.readFileSync('app/bie.js','utf8')+'\n'+fs.readFileSync('app/bie_rounds.js','utf8'),ctx);
const candidates=Array.from({length:12},(_,i)=>({entryId:String(i),name:'Dog '+i,hound:{entryId:String(i),callName:'Dog '+i,breed:'WH'}}));trial={scorebook:{bif:{eventType:'BIE',elimination:true,dogsPerCourse:2,judge1:'Judge',selectedEntryIds:candidates.map(c=>c.entryId),bieCandidates:candidates}}};
(async()=>{await ctx.startManualBie();assert(trial.scorebook.bif.draw.manualDraft);assert.equal(trial.scorebook.bif.draw.courses[0].hounds.length,0);
for(let i=0;i<6;i++){if(i)trial.scorebook.bif.draw.courses.push({id:'c'+i,number:i+1,hounds:[]});const id=trial.scorebook.bif.draw.courses[i].id;ctx.assignBieDraftHound(String(i*2),id);ctx.assignBieDraftHound(String(i*2+1),id);}
ctx.finishManualBie();assert.equal(trial.scorebook.bif.draw.manualDraft,false);assert.equal(trial.scorebook.bif.draw.courses.length,6);const unchanged=JSON.stringify(trial);ctx.advanceBieRound();assert.equal(JSON.stringify(trial),unchanged);
function choose(){for(const c of trial.scorebook.bif.draw.courses)ctx.setBieCourseWinner(c.id,String(c.hounds[0].entryId));}
choose();trial.scorebook.bif.outcomes={'0':{judge1:'85',score:'85'}};const first=JSON.stringify(trial.scorebook.bif.draw);ctx.advanceBieRound();assert.equal(trial.scorebook.bif.draw.courses.length,3);assert.equal(trial.scorebook.bif.selectedEntryIds.length,6);assert.equal(JSON.stringify(trial.scorebook.bif.roundHistory[0].draw),first);assert.equal(trial.scorebook.bif.roundHistory[0].outcomes['0'].score,'85');choose();ctx.advanceBieRound();assert.equal(trial.scorebook.bif.draw.courses.length,1);assert.equal(trial.scorebook.bif.draw.courses[0].hounds.length,3);assert.equal(trial.scorebook.bif.roundHistory.length,2);choose();ctx.advanceBieRound();assert.equal(trial.scorebook.bif.finalWinner,'0');
confirm=false;const completed=JSON.stringify(trial);await ctx.reopenBieRoundForCorrection('main',0);assert.equal(JSON.stringify(trial),completed);
confirm=true;await ctx.reopenBieRoundForCorrection('main',0);assert.equal(trial.scorebook.bif.roundHistory.length,0);assert.equal(trial.scorebook.bif.finalWinner,'');assert.equal(JSON.stringify(trial.scorebook.bif.draw),first);assert.equal(trial.scorebook.bif.outcomes['0'].score,'85');assert.equal(trial.scorebook.bif.selectedEntryIds.length,12);
trial.scorebook.bif.finalWinner='';trial.scorebook.bif.elimination=false;const standard=JSON.stringify(trial);ctx.advanceBieRound();assert.equal(JSON.stringify(trial),standard);trial.archivedAt='now';const prior=writes;ctx.assignBieDraftHound('0','c');ctx.finishManualBie();assert.equal(writes,prior);
console.log('Manual setup and optional elimination passed: 12 -> 6 -> 3 -> winner, unresolved-course guard, retained history/scores, cancel and reopen correction, standard mode and archive guards.');})().catch(e=>{console.error(e);process.exitCode=1});
