const {chromium}=require('C:/Users/johns/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
const p=await b.newPage();let phase='idle';const actions=[];
await p.route('http://update.test/**',r=>{const path=new URL(r.request().url()).pathname;if(path==='/')return r.fulfill({contentType:'text/html',body:'<p id="installedVersionText"></p><div id="availableVersions"></div><div id="versionFolderLink"></div><input id="includeBetaVersions" type="checkbox" checked><p id="versionCheckMessage"></p><button id="checkVersionsButton"></button><div id="programUpdateStatus"></div>'});const action=path.split('update-')[1];if(action==='prepare'){phase='ready';actions.push(action)}if(action==='cancel'){phase='idle';actions.push(action)}return r.fulfill({json:{ok:true,supported:true,platform:'windows',phase,token:'test-token',message:phase}})});
await p.goto('http://update.test/');await p.evaluate(()=>window.appVersionInfo={version:'0.4.0',channel:'beta'});await p.addScriptTag({content:fs.readFileSync('app/updates.js','utf8')});
await p.evaluate(()=>{versionBrowserIndex={schemaVersion:1,versions:[{version:'0.4.1',channel:'beta',status:'available',updates:{windows:{url:'example'}}}]};return refreshProgramUpdate()});
await p.getByRole('button',{name:'Prepare Update'}).click();await p.getByRole('button',{name:'Install and Restart'}).waitFor();assert(await p.getByRole('button',{name:'Prepare Update'}).isDisabled());await p.getByRole('button',{name:'Cancel Update'}).click();await p.waitForFunction(()=>document.querySelector('#programUpdateStatus').textContent==='idle');assert.deepEqual(actions,['prepare','cancel']);console.log('Updater browser prepare, install control, busy state and cancel checks passed.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
