const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({normalizeBreedCode:value=>String(value || '').trim().toUpperCase()});
vm.runInContext(fs.readFileSync('app/specialty_stakes.js','utf8'), context);
const pair = context.specialtyPairEntries;
const entries = ['a','b','c','d'].map(id=>({id,houndId:id,breed:'RR',additionalKennel:true,additionalBreeder:true,ownerSeparationGroup:'Z'}));
let result = pair(entries,'Kennel','a','b');
assert.equal(result[1].specialtyKennelPartnerId,'a');
assert.equal(entries[0].specialtyKennelPartnerId,undefined);
result = pair(result,'Breeder','a','c');
assert.equal(result[0].specialtyKennelPartnerId,'b');
assert.equal(result[2].specialtyBreederPartnerId,'a');
assert.throws(()=>pair(result,'Kennel','c','b'),/already has a partner/);
assert.throws(()=>pair(result,'Kennel','a','a'),/different hound/);
assert.throws(()=>pair(result.map(e=>e.id==='d'?{...e,breed:'WH'}:e),'Kennel','a','d'),/same breed/);
assert.throws(()=>pair(result.map(e=>e.id==='d'?{...e,houndId:'a'}:e),'Kennel','a','d'),/different hound/);
result = pair(result,'Kennel','a','d');
assert.equal(result[1].specialtyKennelPartnerId,'');
assert.equal(result[3].specialtyKennelPartnerId,'a');
result = pair(result,'Kennel','a','');
assert.equal(result[3].specialtyKennelPartnerId,'');
assert.ok(result.every(e=>e.ownerSeparationGroup==='Z'));
console.log('Specialty pairing regression checks passed.');